# Generated by Django 4.2.6 on 2024-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('button_text', models.CharField(default='Contact Us', max_length=50)),
                ('button_link', models.CharField(default='/contact', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
