# Generated by Django 4.2.6 on 2024-02-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_service_servicefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text="FontAwesome icon class, e.g., 'fa-users'", max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, help_text="Number to display with a '+' sign if needed.", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for countries or additional info.', null=True)),
            ],
        ),
    ]
