# Generated by Django 4.2.6 on 2024-02-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('documents', models.FileField(upload_to='documents/')),
                ('coc', models.FileField(upload_to='cocs/', verbose_name='Certificate of Competency')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profession')),
            ],
        ),
    ]
