# Generated by Django 4.2.6 on 2024-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profession_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='The name of the website.', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Logo of the website.', null=True, upload_to='logos/')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL.', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL.', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL.', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL.', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL.', null=True)),
                ('email', models.EmailField(help_text='Contact email address.', max_length=254)),
                ('phone_number', models.CharField(help_text='Contact phone number.', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address.', null=True)),
                ('copyright_text', models.TextField(blank=True, help_text='Copyright text for the footer.', null=True)),
                ('about_us_text', models.TextField(blank=True, help_text='Short description about the website or company for the footer.', null=True)),
                ('google_map_iframe', models.TextField(blank=True, help_text='Google Map iframe code for the contact page.', null=True)),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
