# Generated by Django 4.2.6 on 2024-02-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_websitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the image', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description of the image')),
                ('image', models.ImageField(help_text='Upload the gallery image here', upload_to='gallery_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='The date and time this image was added')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-date_added'],
            },
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='coc',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='profession',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='desired_country',
            field=models.CharField(blank=True, choices=[('jordan', 'Jordan'), ('saudi_arabia', 'Saudi Arabia'), ('dubai', 'Dubai'), ('qatar', 'Qatar')], max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='passport',
            field=models.FileField(blank=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='region',
            field=models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('oromia', 'Oromia')], default='Addis Ababa', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6),
        ),
    ]
