# Generated by Django 4.2.6 on 2024-02-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='region',
            field=models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('oromia', 'Oromia'), ('amhara', 'Amhara'), ('tigray', 'Tigray')], default='Addis Ababa', max_length=50),
        ),
    ]
