# Generated by Django 4.2.6 on 2024-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_jobapplication_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='region',
            field=models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('oromia', 'Oromia'), ('amhara', 'Amhara'), ('tigray', 'Tigray'), ('south', 'South'), ('somali', 'Somali'), ('afar', 'Afar')], default='Addis Ababa', max_length=50),
        ),
    ]
