# Generated by Django 5.0.2 on 2024-03-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_visastatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisaStatus',
        ),
    ]
